-- ==============================================================================
-- SNOWOPS INTEL LITE — GIT-BASED SQL-ONLY DEPLOYMENT
-- ==============================================================================
-- ZERO-CLONE INSTALL: Paste this into a Snowsight worksheet and run as ACCOUNTADMIN.
-- This deploys the LITE (free) edition directly from GitHub.
--
-- For the full Pro edition, use: setup/setup_git_deploy.sql
-- ==============================================================================

USE ROLE ACCOUNTADMIN;

-- ╔══════════════════════════════════════════════════════════════════════╗
-- ║ 1. INFRASTRUCTURE                                                  ║
-- ╚══════════════════════════════════════════════════════════════════════╝

CREATE DATABASE IF NOT EXISTS SNOWFLAKE_OPS_INTELLIGENCE;
USE DATABASE SNOWFLAKE_OPS_INTELLIGENCE;

CREATE SCHEMA IF NOT EXISTS APP_DATA;
CREATE SCHEMA IF NOT EXISTS APP_CONTEXT;
CREATE SCHEMA IF NOT EXISTS APP_ANALYTICS;

CREATE WAREHOUSE IF NOT EXISTS SNOWOPS_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE SNOWOPS_WH;


-- ╔══════════════════════════════════════════════════════════════════════╗
-- ║ 2. CORE TABLES                                                     ║
-- ╚══════════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS APP_CONTEXT.PLATFORM_SETTINGS (
    SETTING_KEY VARCHAR(100) PRIMARY KEY,
    SETTING_VALUE VARCHAR(1000),
    DESCRIPTION VARCHAR(500),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS APP_CONTEXT.WAREHOUSE_CONTEXT (
    WAREHOUSE_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    WAREHOUSE_NAME VARCHAR(255) NOT NULL UNIQUE,
    PURPOSE VARCHAR(50) DEFAULT 'GENERAL',
    SIZE VARCHAR(20),
    COST_PROFILE VARCHAR(20) DEFAULT 'BALANCED',
    OWNER_TEAM VARCHAR(255),
    NOTES VARCHAR(2000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS APP_CONTEXT.BUDGET_ALERTS (
    ALERT_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    ALERT_NAME VARCHAR(255) NOT NULL,
    ALERT_TYPE VARCHAR(50),
    TARGET_NAME VARCHAR(255),
    THRESHOLD_CREDITS FLOAT,
    THRESHOLD_PERCENTAGE FLOAT,
    THRESHOLD_VALUE FLOAT,
    CONDITION_OP VARCHAR(50) DEFAULT '>',
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS APP_ANALYTICS.DAILY_COST_SNAPSHOT (
    SNAPSHOT_DATE DATE PRIMARY KEY,
    TOTAL_CREDITS_USED FLOAT,
    COMPUTE_CREDITS FLOAT,
    STORAGE_CREDITS FLOAT,
    CLOUD_SERVICES_CREDITS FLOAT,
    DATA_TRANSFER_CREDITS FLOAT,
    WAREHOUSE_COUNT NUMBER,
    QUERY_COUNT NUMBER,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS APP_ANALYTICS.WAREHOUSE_DAILY_METRICS (
    METRIC_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    METRIC_DATE DATE,
    WAREHOUSE_NAME VARCHAR(255),
    CREDITS_USED FLOAT,
    QUERY_COUNT NUMBER,
    AVG_EXECUTION_TIME_MS FLOAT,
    CACHE_HIT_RATIO FLOAT,
    BYTES_SCANNED NUMBER,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (METRIC_DATE, WAREHOUSE_NAME)
);

CREATE TABLE IF NOT EXISTS APP_ANALYTICS.QUERY_BENCHMARK (
    BENCHMARK_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    QUERY_TEXT VARCHAR(10000),
    QUERY_HASH VARCHAR(64),
    RUN_TYPE VARCHAR(20),
    PREDICTED_COST_CREDITS FLOAT,
    ACTUAL_COST_CREDITS FLOAT,
    RUN_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


-- ╔══════════════════════════════════════════════════════════════════════╗
-- ║ 3. DEFAULT SETTINGS + TELEMETRY                                    ║
-- ╚══════════════════════════════════════════════════════════════════════╝

INSERT INTO APP_CONTEXT.PLATFORM_SETTINGS (SETTING_KEY, SETTING_VALUE, DESCRIPTION)
SELECT 'COST_PER_CREDIT', '3.00', 'Dollar cost per Snowflake credit'
WHERE NOT EXISTS (SELECT 1 FROM APP_CONTEXT.PLATFORM_SETTINGS WHERE SETTING_KEY = 'COST_PER_CREDIT');

INSERT INTO APP_CONTEXT.PLATFORM_SETTINGS (SETTING_KEY, SETTING_VALUE, DESCRIPTION)
SELECT 'MONTHLY_BUDGET_CREDITS', '1000', 'Monthly credit budget limit'
WHERE NOT EXISTS (SELECT 1 FROM APP_CONTEXT.PLATFORM_SETTINGS WHERE SETTING_KEY = 'MONTHLY_BUDGET_CREDITS');

-- Telemetry (anonymous usage data — disable by setting to FALSE)
INSERT INTO APP_CONTEXT.PLATFORM_SETTINGS (SETTING_KEY, SETTING_VALUE, DESCRIPTION)
SELECT 'TELEMETRY_ENABLED', 'TRUE', 'Enable anonymous usage telemetry. Disable anytime in Settings.'
WHERE NOT EXISTS (SELECT 1 FROM APP_CONTEXT.PLATFORM_SETTINGS WHERE SETTING_KEY = 'TELEMETRY_ENABLED');

INSERT INTO APP_CONTEXT.PLATFORM_SETTINGS (SETTING_KEY, SETTING_VALUE, DESCRIPTION)
SELECT 'POSTHOG_API_KEY', 'phc_W89NRd31nyEXwMDNHgvW1kxycaKPLq2SqKjm9RuKpzH', 'PostHog project API key (anonymous telemetry)'
WHERE NOT EXISTS (SELECT 1 FROM APP_CONTEXT.PLATFORM_SETTINGS WHERE SETTING_KEY = 'POSTHOG_API_KEY');

INSERT INTO APP_CONTEXT.PLATFORM_SETTINGS (SETTING_KEY, SETTING_VALUE, DESCRIPTION)
SELECT 'POSTHOG_HOST', 'https://us.i.posthog.com', 'PostHog API endpoint'
WHERE NOT EXISTS (SELECT 1 FROM APP_CONTEXT.PLATFORM_SETTINGS WHERE SETTING_KEY = 'POSTHOG_HOST');


-- ╔══════════════════════════════════════════════════════════════════════╗
-- ║ 4. GRANTS                                                          ║
-- ╚══════════════════════════════════════════════════════════════════════╝

GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE PUBLIC;
GRANT USAGE ON DATABASE SNOWFLAKE_OPS_INTELLIGENCE TO ROLE PUBLIC;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SNOWFLAKE_OPS_INTELLIGENCE TO ROLE PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA APP_CONTEXT TO ROLE PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA APP_ANALYTICS TO ROLE PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA APP_CONTEXT TO ROLE PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA APP_ANALYTICS TO ROLE PUBLIC;


-- ╔══════════════════════════════════════════════════════════════════════╗
-- ║ 5. GIT DEPLOY — LITE EDITION FROM GITHUB                          ║
-- ╚══════════════════════════════════════════════════════════════════════╝

-- API Integration for GitHub
CREATE OR REPLACE API INTEGRATION SNOWOPS_GIT_INTEGRATION
  API_PROVIDER = GIT_HTTPS_API
  API_ALLOWED_PREFIXES = ('https://github.com/devbysatyam/')
  ENABLED = TRUE;

-- Stage for app files
CREATE STAGE IF NOT EXISTS APP_ANALYTICS.STREAMLIT_STAGE
  DIRECTORY = (ENABLE = TRUE);

-- Git Repository object
CREATE OR REPLACE GIT REPOSITORY APP_DATA.SNOWOPS_REPO
  API_INTEGRATION = SNOWOPS_GIT_INTEGRATION
  ORIGIN = 'https://github.com/devbysatyam/snowops_intel_lite.git';

ALTER GIT REPOSITORY APP_DATA.SNOWOPS_REPO FETCH;

-- Deploy LITE Streamlit app from Git
CREATE OR REPLACE STREAMLIT APP_ANALYTICS.SNOWOPS_INTEL_LITE
  ROOT_LOCATION = '@APP_DATA.SNOWOPS_REPO/branches/main/'
  MAIN_FILE = 'streamlit_app.py'
  QUERY_WAREHOUSE = SNOWOPS_WH
  TITLE = 'SnowOps Intel Lite'
  COMMENT = 'Lite edition — deployed via Git integration';

GRANT USAGE ON STREAMLIT APP_ANALYTICS.SNOWOPS_INTEL_LITE TO ROLE PUBLIC;


-- ╔══════════════════════════════════════════════════════════════════════╗
-- ║ SETUP COMPLETE ✅                                                  ║
-- ╚══════════════════════════════════════════════════════════════════════╝
-- Your Lite app is now live!
-- Navigate to: Snowsight → Projects → Streamlit → SNOWOPS_INTEL_LITE
--
-- To update when new code is pushed:
--   ALTER GIT REPOSITORY APP_DATA.SNOWOPS_REPO FETCH;
--
-- To upgrade to Pro later:
--   Run setup/setup_git_deploy.sql from the same GitHub repo
-- ==============================================================================

SELECT '✅ SnowOps Intel Lite deployed! Open Snowsight → Streamlit → SNOWOPS_INTEL_LITE' AS STATUS;
